[package]
name = "mcp_postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = "0.7.12"
tokio = {version = "1.42.0", features = ["rt-multi-thread","macros"]}
serde = "1.0.217"
serde_json = { version = "1.0.134", features = ["default"]}
